include: [".well-known"]

#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1538265374                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://nikolafranicevic.com              # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Whether you are going through difficult times, are just bored, or sharing inspirational quotes with your friends, Spontaneous has you covered.


enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nikola Franičević
your_link                                 : https://nikolafranicevic.com/
your_city                                 : Zagreb
email_address                             : nikola007f@gmail.com
medium_username                           : franicevicnikola
twitter_username                          : FranicevicNiko
github_username                           : FranicevicNikola
youtube_username                          : Nikola Franičević



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Read Through Hundreds of Quotes
    description                           : Get your daily dose of completely randomized quotes.
    fontawesome_icon_name                 : magic

  - title                                 : Get Spontaneous reminders
    description                           : Get notified with random quotes every day.
    fontawesome_icon_name                 : bell

  - title                                 : Save Quotes
    description                           : Save the quotes you like for later.
    fontawesome_icon_name                 : save

  - title                                 : Search Saved Quotes
    description                           : No need to scroll infinitely to find your favorite quotes, just search for them.
    fontawesome_icon_name                 : search

  - title                                 : Share Quotes
    description                           : Share quotes with your friends and family.
    fontawesome_icon_name                 : share

  - title                                 : Shake to Undo
    description                           : Accidentally deleted a quote? Shake the device to undo the deletion!
    fontawesome_icon_name                 : undo

  - title                                 : Display Your Favorite Quote Using a Widget
    description                           : Read favorite quotes on your home screen now, featuring widget support.
    fontawesome_icon_name                 : mobile

  - title                                 : Text to Speech
    description                           : Too lazy to read? How about listening to quotes?
    fontawesome_icon_name                 : volume-up

  - title                                 : Works Offline
    description                           : No need for an internet connection to explore new quotes.
    fontawesome_icon_name                 : wifi

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#000000"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#000000"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
